name: Run Hardhat Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci
        working-directory: backend

      - name: Compile contracts
        run: npx hardhat compile
        working-directory: backend

      - name: Run tests
        run: npx hardhat test
        working-directory: backend
